# version: "3.9"

services:
    backend:
        build: ./backend
        ports:
            - "5005:5005"
        volumes:
            - ./backend:/app
        environment:
            - PORT=5005
        depends_on:
            - db
        networks:
            - botano_network
    frontend:
        build: ./frontend
        platform: linux/amd64
        ports:
            - "5173:5173"
        volumes:
            - ./frontend:/app
            - /app/node_modules # Запобігає перезапису з хоста
        environment:
            - NODE_ENV=development
        networks:
            - botano_network
    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: spor_shop
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - botano_network
volumes:
    mysql_data:
networks:
    botano_network:
        driver: bridge
